version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github_actions:
        patterns:
          - "*"
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
    groups:
      ruby_default:
        patterns:
          - "*"
